title: "Ali Mohamed | Data Analyst Portfolio"
description: "I'm a Data Analyst with expertise in SQL, Python, Power BI, and Excel. I love uncovering trends, solving problems with data, and building insightful dashboards."
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

