title: "Ali Mohamed | Data Analyst Portfolio"
description: "Data Analyst skilled in SQL, Power BI, Excel, and Python. Passionate about transforming raw data into meaningful insights."
theme: jekyll-theme-minimal
